<?xml version="1.0" encoding="UTF-8" ?>
<Package name="TapperSample" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="." xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="Untitled/behavior_2" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="behavior_2" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="contents" src="html/css/contents.css" />
        <File name="normalize" src="html/css/normalize.css" />
        <File name="index" src="html/index.html" />
        <File name="contents" src="html/js/contents.js" />
        <File name="tapper" src="html/js/tapper.js" />
        <File name="omocha_robot" src="html/img/preloads/omocha_robot.png" />
        <File name="init_data" src="init_data.json" />
        <File name="hqdefault" src="html/img/hqdefault.jpg" />
        <File name="main" src="html/img/preloads/main.jpg" />
        <File name="unfinished1" src="html/img/unfinished1.jpg" />
        <File name="unfinished2" src="html/img/unfinished2.jpg" />
        <File name="unfinished3" src="html/img/unfinished3.jpg" />
        <File name="urllib" src="lib/url/urllib.py" />
        <File name="urllib2" src="lib/url/urllib2.py" />
        <File name="__init__" src="lib/certifi/__init__.py" />
        <File name="__main__" src="lib/certifi/__main__.py" />
        <File name="cacert" src="lib/certifi/cacert.pem" />
        <File name="core" src="lib/certifi/core.py" />
        <File name="old_root" src="lib/certifi/old_root.pem" />
        <File name="weak" src="lib/certifi/weak.pem" />
        <File name="__init__" src="lib/chardet/__init__.py" />
        <File name="big5freq" src="lib/chardet/big5freq.py" />
        <File name="big5prober" src="lib/chardet/big5prober.py" />
        <File name="chardistribution" src="lib/chardet/chardistribution.py" />
        <File name="charsetgroupprober" src="lib/chardet/charsetgroupprober.py" />
        <File name="charsetprober" src="lib/chardet/charsetprober.py" />
        <File name="__init__" src="lib/chardet/cli/__init__.py" />
        <File name="chardetect" src="lib/chardet/cli/chardetect.py" />
        <File name="codingstatemachine" src="lib/chardet/codingstatemachine.py" />
        <File name="compat" src="lib/chardet/compat.py" />
        <File name="cp949prober" src="lib/chardet/cp949prober.py" />
        <File name="enums" src="lib/chardet/enums.py" />
        <File name="escprober" src="lib/chardet/escprober.py" />
        <File name="escsm" src="lib/chardet/escsm.py" />
        <File name="eucjpprober" src="lib/chardet/eucjpprober.py" />
        <File name="euckrfreq" src="lib/chardet/euckrfreq.py" />
        <File name="euckrprober" src="lib/chardet/euckrprober.py" />
        <File name="euctwfreq" src="lib/chardet/euctwfreq.py" />
        <File name="euctwprober" src="lib/chardet/euctwprober.py" />
        <File name="gb2312freq" src="lib/chardet/gb2312freq.py" />
        <File name="gb2312prober" src="lib/chardet/gb2312prober.py" />
        <File name="hebrewprober" src="lib/chardet/hebrewprober.py" />
        <File name="jisfreq" src="lib/chardet/jisfreq.py" />
        <File name="jpcntx" src="lib/chardet/jpcntx.py" />
        <File name="langbulgarianmodel" src="lib/chardet/langbulgarianmodel.py" />
        <File name="langcyrillicmodel" src="lib/chardet/langcyrillicmodel.py" />
        <File name="langgreekmodel" src="lib/chardet/langgreekmodel.py" />
        <File name="langhebrewmodel" src="lib/chardet/langhebrewmodel.py" />
        <File name="langhungarianmodel" src="lib/chardet/langhungarianmodel.py" />
        <File name="langthaimodel" src="lib/chardet/langthaimodel.py" />
        <File name="langturkishmodel" src="lib/chardet/langturkishmodel.py" />
        <File name="latin1prober" src="lib/chardet/latin1prober.py" />
        <File name="mbcharsetprober" src="lib/chardet/mbcharsetprober.py" />
        <File name="mbcsgroupprober" src="lib/chardet/mbcsgroupprober.py" />
        <File name="mbcssm" src="lib/chardet/mbcssm.py" />
        <File name="sbcharsetprober" src="lib/chardet/sbcharsetprober.py" />
        <File name="sbcsgroupprober" src="lib/chardet/sbcsgroupprober.py" />
        <File name="sjisprober" src="lib/chardet/sjisprober.py" />
        <File name="universaldetector" src="lib/chardet/universaldetector.py" />
        <File name="utf8prober" src="lib/chardet/utf8prober.py" />
        <File name="version" src="lib/chardet/version.py" />
        <File name="__init__" src="lib/idna/__init__.py" />
        <File name="codec" src="lib/idna/codec.py" />
        <File name="compat" src="lib/idna/compat.py" />
        <File name="core" src="lib/idna/core.py" />
        <File name="idnadata" src="lib/idna/idnadata.py" />
        <File name="intranges" src="lib/idna/intranges.py" />
        <File name="package_data" src="lib/idna/package_data.py" />
        <File name="uts46data" src="lib/idna/uts46data.py" />
        <File name="__init__" src="lib/requests/__init__.py" />
        <File name="__version__" src="lib/requests/__version__.py" />
        <File name="_internal_utils" src="lib/requests/_internal_utils.py" />
        <File name="adapters" src="lib/requests/adapters.py" />
        <File name="api" src="lib/requests/api.py" />
        <File name="auth" src="lib/requests/auth.py" />
        <File name="certs" src="lib/requests/certs.py" />
        <File name="compat" src="lib/requests/compat.py" />
        <File name="cookies" src="lib/requests/cookies.py" />
        <File name="exceptions" src="lib/requests/exceptions.py" />
        <File name="help" src="lib/requests/help.py" />
        <File name="hooks" src="lib/requests/hooks.py" />
        <File name="models" src="lib/requests/models.py" />
        <File name="packages" src="lib/requests/packages.py" />
        <File name="sessions" src="lib/requests/sessions.py" />
        <File name="status_codes" src="lib/requests/status_codes.py" />
        <File name="structures" src="lib/requests/structures.py" />
        <File name="utils" src="lib/requests/utils.py" />
        <File name="__init__" src="lib/urllib3/__init__.py" />
        <File name="_collections" src="lib/urllib3/_collections.py" />
        <File name="connection" src="lib/urllib3/connection.py" />
        <File name="connectionpool" src="lib/urllib3/connectionpool.py" />
        <File name="__init__" src="lib/urllib3/contrib/__init__.py" />
        <File name="__init__" src="lib/urllib3/contrib/_securetransport/__init__.py" />
        <File name="bindings" src="lib/urllib3/contrib/_securetransport/bindings.py" />
        <File name="low_level" src="lib/urllib3/contrib/_securetransport/low_level.py" />
        <File name="appengine" src="lib/urllib3/contrib/appengine.py" />
        <File name="ntlmpool" src="lib/urllib3/contrib/ntlmpool.py" />
        <File name="pyopenssl" src="lib/urllib3/contrib/pyopenssl.py" />
        <File name="securetransport" src="lib/urllib3/contrib/securetransport.py" />
        <File name="socks" src="lib/urllib3/contrib/socks.py" />
        <File name="exceptions" src="lib/urllib3/exceptions.py" />
        <File name="fields" src="lib/urllib3/fields.py" />
        <File name="filepost" src="lib/urllib3/filepost.py" />
        <File name="__init__" src="lib/urllib3/packages/__init__.py" />
        <File name="__init__" src="lib/urllib3/packages/backports/__init__.py" />
        <File name="makefile" src="lib/urllib3/packages/backports/makefile.py" />
        <File name="ordered_dict" src="lib/urllib3/packages/ordered_dict.py" />
        <File name="six" src="lib/urllib3/packages/six.py" />
        <File name="__init__" src="lib/urllib3/packages/ssl_match_hostname/__init__.py" />
        <File name="_implementation" src="lib/urllib3/packages/ssl_match_hostname/_implementation.py" />
        <File name="poolmanager" src="lib/urllib3/poolmanager.py" />
        <File name="request" src="lib/urllib3/request.py" />
        <File name="response" src="lib/urllib3/response.py" />
        <File name="__init__" src="lib/urllib3/util/__init__.py" />
        <File name="connection" src="lib/urllib3/util/connection.py" />
        <File name="request" src="lib/urllib3/util/request.py" />
        <File name="response" src="lib/urllib3/util/response.py" />
        <File name="retry" src="lib/urllib3/util/retry.py" />
        <File name="selectors" src="lib/urllib3/util/selectors.py" />
        <File name="ssl_" src="lib/urllib3/util/ssl_.py" />
        <File name="timeout" src="lib/urllib3/util/timeout.py" />
        <File name="url" src="lib/urllib3/util/url.py" />
        <File name="wait" src="lib/urllib3/util/wait.py" />
        <File name="__init__" src="lib/utils/__init__.py" />
        <File name="bools" src="lib/utils/bools.py" />
        <File name="dates" src="lib/utils/dates.py" />
        <File name="__init__" src="lib/utils/dicts/__init__.py" />
        <File name="chained_dict" src="lib/utils/dicts/chained_dict.py" />
        <File name="helpers" src="lib/utils/dicts/helpers.py" />
        <File name="limited_dict" src="lib/utils/dicts/limited_dict.py" />
        <File name="enum" src="lib/utils/enum.py" />
        <File name="lists" src="lib/utils/lists.py" />
        <File name="math" src="lib/utils/math.py" />
        <File name="objects" src="lib/utils/objects.py" />
        <File name="Untitled" src="Untitled/Untitled.pml" />
        <File name="camera1" src="Untitled/behavior_2/camera1.ogg" />
        <File name="contents" src="Untitled/html/css/contents.css" />
        <File name="normalize" src="Untitled/html/css/normalize.css" />
        <File name="image" src="Untitled/html/image.jpg" />
        <File name="hqdefault" src="Untitled/html/img/hqdefault.jpg" />
        <File name="main" src="Untitled/html/img/preloads/main.jpg" />
        <File name="omocha_robot" src="Untitled/html/img/preloads/omocha_robot.png" />
        <File name="unfinished1" src="Untitled/html/img/unfinished1.jpg" />
        <File name="unfinished2" src="Untitled/html/img/unfinished2.jpg" />
        <File name="unfinished3" src="Untitled/html/img/unfinished3.jpg" />
        <File name="index" src="Untitled/html/index.html" />
        <File name="contents" src="Untitled/html/js/contents.js" />
        <File name="tapper" src="Untitled/html/js/tapper.js" />
        <File name="__init__" src="Untitled/lib/certifi/__init__.py" />
        <File name="__main__" src="Untitled/lib/certifi/__main__.py" />
        <File name="cacert" src="Untitled/lib/certifi/cacert.pem" />
        <File name="core" src="Untitled/lib/certifi/core.py" />
        <File name="old_root" src="Untitled/lib/certifi/old_root.pem" />
        <File name="weak" src="Untitled/lib/certifi/weak.pem" />
        <File name="__init__" src="Untitled/lib/chardet/__init__.py" />
        <File name="big5freq" src="Untitled/lib/chardet/big5freq.py" />
        <File name="big5prober" src="Untitled/lib/chardet/big5prober.py" />
        <File name="chardistribution" src="Untitled/lib/chardet/chardistribution.py" />
        <File name="charsetgroupprober" src="Untitled/lib/chardet/charsetgroupprober.py" />
        <File name="charsetprober" src="Untitled/lib/chardet/charsetprober.py" />
        <File name="__init__" src="Untitled/lib/chardet/cli/__init__.py" />
        <File name="chardetect" src="Untitled/lib/chardet/cli/chardetect.py" />
        <File name="codingstatemachine" src="Untitled/lib/chardet/codingstatemachine.py" />
        <File name="compat" src="Untitled/lib/chardet/compat.py" />
        <File name="cp949prober" src="Untitled/lib/chardet/cp949prober.py" />
        <File name="enums" src="Untitled/lib/chardet/enums.py" />
        <File name="escprober" src="Untitled/lib/chardet/escprober.py" />
        <File name="escsm" src="Untitled/lib/chardet/escsm.py" />
        <File name="eucjpprober" src="Untitled/lib/chardet/eucjpprober.py" />
        <File name="euckrfreq" src="Untitled/lib/chardet/euckrfreq.py" />
        <File name="euckrprober" src="Untitled/lib/chardet/euckrprober.py" />
        <File name="euctwfreq" src="Untitled/lib/chardet/euctwfreq.py" />
        <File name="euctwprober" src="Untitled/lib/chardet/euctwprober.py" />
        <File name="gb2312freq" src="Untitled/lib/chardet/gb2312freq.py" />
        <File name="gb2312prober" src="Untitled/lib/chardet/gb2312prober.py" />
        <File name="hebrewprober" src="Untitled/lib/chardet/hebrewprober.py" />
        <File name="jisfreq" src="Untitled/lib/chardet/jisfreq.py" />
        <File name="jpcntx" src="Untitled/lib/chardet/jpcntx.py" />
        <File name="langbulgarianmodel" src="Untitled/lib/chardet/langbulgarianmodel.py" />
        <File name="langcyrillicmodel" src="Untitled/lib/chardet/langcyrillicmodel.py" />
        <File name="langgreekmodel" src="Untitled/lib/chardet/langgreekmodel.py" />
        <File name="langhebrewmodel" src="Untitled/lib/chardet/langhebrewmodel.py" />
        <File name="langhungarianmodel" src="Untitled/lib/chardet/langhungarianmodel.py" />
        <File name="langthaimodel" src="Untitled/lib/chardet/langthaimodel.py" />
        <File name="langturkishmodel" src="Untitled/lib/chardet/langturkishmodel.py" />
        <File name="latin1prober" src="Untitled/lib/chardet/latin1prober.py" />
        <File name="mbcharsetprober" src="Untitled/lib/chardet/mbcharsetprober.py" />
        <File name="mbcsgroupprober" src="Untitled/lib/chardet/mbcsgroupprober.py" />
        <File name="mbcssm" src="Untitled/lib/chardet/mbcssm.py" />
        <File name="sbcharsetprober" src="Untitled/lib/chardet/sbcharsetprober.py" />
        <File name="sbcsgroupprober" src="Untitled/lib/chardet/sbcsgroupprober.py" />
        <File name="sjisprober" src="Untitled/lib/chardet/sjisprober.py" />
        <File name="universaldetector" src="Untitled/lib/chardet/universaldetector.py" />
        <File name="utf8prober" src="Untitled/lib/chardet/utf8prober.py" />
        <File name="version" src="Untitled/lib/chardet/version.py" />
        <File name="__init__" src="Untitled/lib/idna/__init__.py" />
        <File name="codec" src="Untitled/lib/idna/codec.py" />
        <File name="compat" src="Untitled/lib/idna/compat.py" />
        <File name="core" src="Untitled/lib/idna/core.py" />
        <File name="idnadata" src="Untitled/lib/idna/idnadata.py" />
        <File name="intranges" src="Untitled/lib/idna/intranges.py" />
        <File name="package_data" src="Untitled/lib/idna/package_data.py" />
        <File name="uts46data" src="Untitled/lib/idna/uts46data.py" />
        <File name="__init__" src="Untitled/lib/requests/__init__.py" />
        <File name="__version__" src="Untitled/lib/requests/__version__.py" />
        <File name="_internal_utils" src="Untitled/lib/requests/_internal_utils.py" />
        <File name="adapters" src="Untitled/lib/requests/adapters.py" />
        <File name="api" src="Untitled/lib/requests/api.py" />
        <File name="auth" src="Untitled/lib/requests/auth.py" />
        <File name="certs" src="Untitled/lib/requests/certs.py" />
        <File name="compat" src="Untitled/lib/requests/compat.py" />
        <File name="cookies" src="Untitled/lib/requests/cookies.py" />
        <File name="exceptions" src="Untitled/lib/requests/exceptions.py" />
        <File name="help" src="Untitled/lib/requests/help.py" />
        <File name="hooks" src="Untitled/lib/requests/hooks.py" />
        <File name="models" src="Untitled/lib/requests/models.py" />
        <File name="packages" src="Untitled/lib/requests/packages.py" />
        <File name="sessions" src="Untitled/lib/requests/sessions.py" />
        <File name="status_codes" src="Untitled/lib/requests/status_codes.py" />
        <File name="structures" src="Untitled/lib/requests/structures.py" />
        <File name="utils" src="Untitled/lib/requests/utils.py" />
        <File name="urllib" src="Untitled/lib/url/urllib.py" />
        <File name="urllib2" src="Untitled/lib/url/urllib2.py" />
        <File name="__init__" src="Untitled/lib/urllib3/__init__.py" />
        <File name="_collections" src="Untitled/lib/urllib3/_collections.py" />
        <File name="connection" src="Untitled/lib/urllib3/connection.py" />
        <File name="connectionpool" src="Untitled/lib/urllib3/connectionpool.py" />
        <File name="__init__" src="Untitled/lib/urllib3/contrib/__init__.py" />
        <File name="__init__" src="Untitled/lib/urllib3/contrib/_securetransport/__init__.py" />
        <File name="bindings" src="Untitled/lib/urllib3/contrib/_securetransport/bindings.py" />
        <File name="low_level" src="Untitled/lib/urllib3/contrib/_securetransport/low_level.py" />
        <File name="appengine" src="Untitled/lib/urllib3/contrib/appengine.py" />
        <File name="ntlmpool" src="Untitled/lib/urllib3/contrib/ntlmpool.py" />
        <File name="pyopenssl" src="Untitled/lib/urllib3/contrib/pyopenssl.py" />
        <File name="securetransport" src="Untitled/lib/urllib3/contrib/securetransport.py" />
        <File name="socks" src="Untitled/lib/urllib3/contrib/socks.py" />
        <File name="exceptions" src="Untitled/lib/urllib3/exceptions.py" />
        <File name="fields" src="Untitled/lib/urllib3/fields.py" />
        <File name="filepost" src="Untitled/lib/urllib3/filepost.py" />
        <File name="__init__" src="Untitled/lib/urllib3/packages/__init__.py" />
        <File name="__init__" src="Untitled/lib/urllib3/packages/backports/__init__.py" />
        <File name="makefile" src="Untitled/lib/urllib3/packages/backports/makefile.py" />
        <File name="ordered_dict" src="Untitled/lib/urllib3/packages/ordered_dict.py" />
        <File name="six" src="Untitled/lib/urllib3/packages/six.py" />
        <File name="__init__" src="Untitled/lib/urllib3/packages/ssl_match_hostname/__init__.py" />
        <File name="_implementation" src="Untitled/lib/urllib3/packages/ssl_match_hostname/_implementation.py" />
        <File name="poolmanager" src="Untitled/lib/urllib3/poolmanager.py" />
        <File name="request" src="Untitled/lib/urllib3/request.py" />
        <File name="response" src="Untitled/lib/urllib3/response.py" />
        <File name="__init__" src="Untitled/lib/urllib3/util/__init__.py" />
        <File name="connection" src="Untitled/lib/urllib3/util/connection.py" />
        <File name="request" src="Untitled/lib/urllib3/util/request.py" />
        <File name="response" src="Untitled/lib/urllib3/util/response.py" />
        <File name="retry" src="Untitled/lib/urllib3/util/retry.py" />
        <File name="selectors" src="Untitled/lib/urllib3/util/selectors.py" />
        <File name="ssl_" src="Untitled/lib/urllib3/util/ssl_.py" />
        <File name="timeout" src="Untitled/lib/urllib3/util/timeout.py" />
        <File name="url" src="Untitled/lib/urllib3/util/url.py" />
        <File name="wait" src="Untitled/lib/urllib3/util/wait.py" />
        <File name="__init__" src="Untitled/lib/utils/__init__.py" />
        <File name="bools" src="Untitled/lib/utils/bools.py" />
        <File name="dates" src="Untitled/lib/utils/dates.py" />
        <File name="__init__" src="Untitled/lib/utils/dicts/__init__.py" />
        <File name="chained_dict" src="Untitled/lib/utils/dicts/chained_dict.py" />
        <File name="helpers" src="Untitled/lib/utils/dicts/helpers.py" />
        <File name="limited_dict" src="Untitled/lib/utils/dicts/limited_dict.py" />
        <File name="enum" src="Untitled/lib/utils/enum.py" />
        <File name="lists" src="Untitled/lib/utils/lists.py" />
        <File name="math" src="Untitled/lib/utils/math.py" />
        <File name="objects" src="Untitled/lib/utils/objects.py" />
        <File name="manifest" src="Untitled/manifest.xml" />
        <File name="camera1" src="behavior_2/camera1.ogg" />
        <File name="test" src="html/test.jpg" />
    </Resources>
    <Topics />
    <IgnoredPaths>
        <Path src=".metadata" />
    </IgnoredPaths>
    <Translations auto-fill="ja_JP">
        <Translation name="translation_ja_JP" src="translations/translation_ja_JP.ts" language="ja_JP" />
    </Translations>
</Package>
